//
//  ContentView.swift
//  App (Generated by SwiftyLaunch 2.0)
//  https://docs.swiftylaun.ch/module/app
//

import AIKit
import AdsKit
import FirebaseKit
import InAppPurchaseKit
import NotifKit
import SharedKit
import SwiftUI

struct ContentView: View {
	@State private var selectedTab = 0
	
	init() { }
	
	var body: some View {
		TabView(selection: $selectedTab) {
			// Vue d'accueil principale
			HomeView()
				.tabItem {
					Label("Accueil", systemImage: "house")
				}
				.tag(0)
				.environment(\.tabSelection, $selectedTab)

			// Vue des listes
			
				.tabItem {
					Label("Listes", systemImage: "list.bullet")
				}
				.tag(1)
				.environment(\.tabSelection, $selectedTab)
			
			// Vue d'ajout de liste
			Text("Ajouter")
				.tabItem {
					Label("Ajouter", systemImage: "plus.circle.fill")
				}
				.tag(2)
				.environment(\.tabSelection, $selectedTab)
			
			// Pre-made Settings View for easy native-looking settings screen.
			SettingsView()
				.tabItem {
					Label("Réglages", systemImage: "gear")
				}
				.tag(3)
				.environment(\.tabSelection, $selectedTab)

			#if DEBUG
			// Use this to create quick settings and toggles to streamline the development process
			DeveloperSettingsView()
				.tabItem {
					Label("Développeur", systemImage: "hammer")
				}
				.tag(4)
				.environment(\.tabSelection, $selectedTab)
			#endif
		}
	}
}

#Preview {
	ContentView()
		.environmentObject(DB())
		.environmentObject(InAppPurchases())
}
